### ISSUE TITLE
Assertion `idx < m_size' failed in Escargot::TightVector::operator[]

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/escargot#236]
###### Escargot version:

```
Checked revision: 958b293

Build command: cmake -H. -Bout -DESCARGOT_HOST=linux -DESCARGOT_ARCH=x64 -DESCARGOT_MODE=debug -DESCARGOT_OUTPUT=bin -GNinja && ninja -C out
```

###### OS:

```
Linux-4.15.0-48-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```javascript
function test0 () {
  var $ = function ($ = ({ $: function () { } })) { }
}
test0()
```

###### Backtrace:

```
escargot: ../src/util/TightVector.h:180: const T& Escargot::TightVector<T, Allocator>::operator[](size_t) const [with T = Escargot::InterpretedCodeBlock*; Allocator = GCUtil::gc_malloc_ignore_off_page_allocator<Escargot::InterpretedCodeBlock*>; size_t = long unsigned int]: Assertion `idx < m_size' failed.

bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6466801 in __GI_abort () at abort.c:79
#2  0x00007ffff645639a in __assert_fail_base (fmt=0x7ffff65dd7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x55555582dd39 "idx < m_size", file=file@entry=0x55555582de19 "../src/util/TightVector.h", line=line@entry=180, function=function@entry=0x55555582f9e0 <Escargot::TightVector<Escargot::InterpretedCodeBlock*, GCUtil::gc_malloc_ignore_off_page_allocator<Escargot::InterpretedCodeBlock*> >::operator[](unsigned long) const::__PRETTY_FUNCTION__> "const T& Escargot::TightVector<T, Allocator>::operator[](size_t) const [with T = Escargot::InterpretedCodeBlock*; Allocator = GCUtil::gc_malloc_ignore_off_page_allocator<Escargot::InterpretedCodeBlock"...) at assert.c:92
#3  0x00007ffff6456412 in __GI___assert_fail (assertion=0x55555582dd39 "idx < m_size", file=0x55555582de19 "../src/util/TightVector.h", line=180, function=0x55555582f9e0 <Escargot::TightVector<Escargot::InterpretedCodeBlock*, GCUtil::gc_malloc_ignore_off_page_allocator<Escargot::InterpretedCodeBlock*> >::operator[](unsigned long) const::__PRETTY_FUNCTION__> "const T& Escargot::TightVector<T, Allocator>::operator[](size_t) const [with T = Escargot::InterpretedCodeBlock*; Allocator = GCUtil::gc_malloc_ignore_off_page_allocator<Escargot::InterpretedCodeBlock"...) at assert.c:101
#4  0x00005555555d6423 in Escargot::TightVector<Escargot::InterpretedCodeBlock*, GCUtil::gc_malloc_ignore_off_page_allocator<Escargot::InterpretedCodeBlock*> >::operator[] (this=0x7ffff45bdd90, idx=1) at ../src/util/TightVector.h:180
#5  0x0000555555658438 in Escargot::esprima::Parser::parseFunctionSourceElements (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:5245
#6  0x0000555555682806 in Escargot::esprima::Parser::parseFunction<Escargot::FunctionExpressionNode, false> (this=0x7fffffff8ee0, node=...) at ../src/parser/esprima_cpp/esprima.cpp:5390
#7  0x0000555555658fd6 in Escargot::esprima::Parser::parseFunctionExpression (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:5424
#8  0x0000555555694c3f in Escargot::esprima::Parser::primaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:1136
#9  0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x555555693de2 <Escargot::esprima::Parser::primaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#10 0x00005555556837ea in Escargot::esprima::Parser::leftHandSideExpressionAllowCall<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2342
#11 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556835ee <Escargot::esprima::Parser::leftHandSideExpressionAllowCall<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#12 0x000055555568d298 in Escargot::esprima::Parser::updateExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2596
#13 0x0000555555676d2c in Escargot::esprima::Parser::unaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2802
#14 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x555555675f9c <Escargot::esprima::Parser::unaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#15 0x0000555555652311 in Escargot::esprima::Parser::parseExponentiationExpression (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2808
#16 0x0000555555677be6 in Escargot::esprima::Parser::inheritCoverGrammar<JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556522b0 <Escargot::esprima::Parser::parseExponentiationExpression()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#17 0x0000555555652763 in Escargot::esprima::Parser::parseBinaryExpression (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2916
#18 0x0000555555677be6 in Escargot::esprima::Parser::inheritCoverGrammar<JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556526d8 <Escargot::esprima::Parser::parseBinaryExpression()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#19 0x000055555568a513 in Escargot::esprima::Parser::conditionalExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:3227
#20 0x0000555555671e41 in Escargot::esprima::Parser::assignmentExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:3384
#21 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x555555671d32 <Escargot::esprima::Parser::assignmentExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#22 0x00005555556ab4e0 in Escargot::esprima::Parser::objectProperty<Escargot::esprima::Parser::PassNode<Escargot::PropertyNode>, true> (this=0x7fffffff8ee0, hasProto=@0x7fffffff649f: false, usedNames=std::__debug::vector of length 0, capacity 0) at ../src/parser/esprima_cpp/esprima.cpp:1722
#23 0x00005555556a2a5e in Escargot::esprima::Parser::objectInitializer<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:1814
#24 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556a29a4 <Escargot::esprima::Parser::objectInitializer<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#25 0x00005555556948a9 in Escargot::esprima::Parser::primaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:1100
#26 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x555555693de2 <Escargot::esprima::Parser::primaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#27 0x00005555556837ea in Escargot::esprima::Parser::leftHandSideExpressionAllowCall<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2342
#28 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556835ee <Escargot::esprima::Parser::leftHandSideExpressionAllowCall<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#29 0x000055555568d298 in Escargot::esprima::Parser::updateExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2596
#30 0x0000555555676d2c in Escargot::esprima::Parser::unaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2802
#31 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x555555675f9c <Escargot::esprima::Parser::unaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#32 0x0000555555652311 in Escargot::esprima::Parser::parseExponentiationExpression (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2808
#33 0x0000555555677be6 in Escargot::esprima::Parser::inheritCoverGrammar<JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556522b0 <Escargot::esprima::Parser::parseExponentiationExpression()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#34 0x0000555555652763 in Escargot::esprima::Parser::parseBinaryExpression (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2916
#35 0x0000555555677be6 in Escargot::esprima::Parser::inheritCoverGrammar<JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556526d8 <Escargot::esprima::Parser::parseBinaryExpression()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#36 0x000055555568a513 in Escargot::esprima::Parser::conditionalExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:3227
#37 0x0000555555671e41 in Escargot::esprima::Parser::assignmentExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:3384
#38 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x555555671d32 <Escargot::esprima::Parser::assignmentExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#39 0x00005555556a167f in Escargot::esprima::Parser::groupExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2130
#40 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556a138c <Escargot::esprima::Parser::groupExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#41 0x000055555569480f in Escargot::esprima::Parser::primaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:1089
#42 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x555555693de2 <Escargot::esprima::Parser::primaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#43 0x00005555556837ea in Escargot::esprima::Parser::leftHandSideExpressionAllowCall<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2342
#44 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556835ee <Escargot::esprima::Parser::leftHandSideExpressionAllowCall<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#45 0x000055555568d298 in Escargot::esprima::Parser::updateExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2596
#46 0x0000555555676d2c in Escargot::esprima::Parser::unaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2802
#47 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x555555675f9c <Escargot::esprima::Parser::unaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#48 0x0000555555652311 in Escargot::esprima::Parser::parseExponentiationExpression (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2808
#49 0x0000555555677be6 in Escargot::esprima::Parser::inheritCoverGrammar<JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556522b0 <Escargot::esprima::Parser::parseExponentiationExpression()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#50 0x0000555555652763 in Escargot::esprima::Parser::parseBinaryExpression (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2916
#51 0x0000555555677be6 in Escargot::esprima::Parser::inheritCoverGrammar<JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556526d8 <Escargot::esprima::Parser::parseBinaryExpression()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#52 0x000055555568a513 in Escargot::esprima::Parser::conditionalExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:3227
#53 0x0000555555671e41 in Escargot::esprima::Parser::assignmentExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:3384
#54 0x000055555567317e in Escargot::esprima::Parser::isolateCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x555555671d32 <Escargot::esprima::Parser::assignmentExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:802
#55 0x000055555564eece in Escargot::esprima::Parser::parsePatternWithDefault (this=0x7fffffff8ee0, params=std::__debug::vector of length 1, capacity 1 = {...}, kind=Escargot::EscargotLexer::KeywordKindEnd) at ../src/parser/esprima_cpp/esprima.cpp:1280
#56 0x000055555564f31c in Escargot::esprima::Parser::parseFormalParameter (this=0x7fffffff8ee0, options=...) at ../src/parser/esprima_cpp/esprima.cpp:1304
#57 0x000055555564f7a1 in Escargot::esprima::Parser::parseFormalParameters (this=0x7fffffff8ee0, firstRestricted=...) at ../src/parser/esprima_cpp/esprima.cpp:1345
#58 0x000055555568273e in Escargot::esprima::Parser::parseFunction<Escargot::FunctionExpressionNode, false> (this=0x7fffffff8ee0, node=...) at ../src/parser/esprima_cpp/esprima.cpp:5380
#59 0x0000555555658fd6 in Escargot::esprima::Parser::parseFunctionExpression (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:5424
#60 0x0000555555694c3f in Escargot::esprima::Parser::primaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:1136
#61 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x555555693de2 <Escargot::esprima::Parser::primaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#62 0x00005555556837ea in Escargot::esprima::Parser::leftHandSideExpressionAllowCall<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2342
#63 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556835ee <Escargot::esprima::Parser::leftHandSideExpressionAllowCall<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#64 0x000055555568d298 in Escargot::esprima::Parser::updateExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2596
#65 0x0000555555676d2c in Escargot::esprima::Parser::unaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2802
#66 0x0000555555677082 in Escargot::esprima::Parser::inheritCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x555555675f9c <Escargot::esprima::Parser::unaryExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#67 0x0000555555652311 in Escargot::esprima::Parser::parseExponentiationExpression (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2808
#68 0x0000555555677be6 in Escargot::esprima::Parser::inheritCoverGrammar<JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556522b0 <Escargot::esprima::Parser::parseExponentiationExpression()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#69 0x0000555555652763 in Escargot::esprima::Parser::parseBinaryExpression (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:2916
#70 0x0000555555677be6 in Escargot::esprima::Parser::inheritCoverGrammar<JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(JSC::Yarr::PassRefPtr<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x5555556526d8 <Escargot::esprima::Parser::parseBinaryExpression()>) at ../src/parser/esprima_cpp/esprima.cpp:896
#71 0x000055555568a513 in Escargot::esprima::Parser::conditionalExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:3227
#72 0x0000555555671e41 in Escargot::esprima::Parser::assignmentExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:3384
#73 0x000055555567317e in Escargot::esprima::Parser::isolateCoverGrammar<Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)()> (this=0x7fffffff8ee0, parseFunction=(Escargot::esprima::Parser::PassNode<Escargot::Node> (Escargot::esprima::Parser::*)(Escargot::esprima::Parser * const)) 0x555555671d32 <Escargot::esprima::Parser::assignmentExpression<Escargot::esprima::Parser::PassNode<Escargot::Node>, true>()>) at ../src/parser/esprima_cpp/esprima.cpp:802
#74 0x0000555555678954 in Escargot::esprima::Parser::variableDeclaration<Escargot::esprima::Parser::PassNode<Escargot::VariableDeclaratorNode>, true> (this=0x7fffffff8ee0, options=...) at ../src/parser/esprima_cpp/esprima.cpp:4061
#75 0x00005555556553c3 in Escargot::esprima::Parser::parseVariableDeclarationList (this=0x7fffffff8ee0, options=...) at ../src/parser/esprima_cpp/esprima.cpp:4082
#76 0x0000555555655634 in Escargot::esprima::Parser::parseVariableStatement (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:4110
#77 0x0000555555656e21 in Escargot::esprima::Parser::parseStatement (this=0x7fffffff8ee0, allowFunctionDeclaration=true) at ../src/parser/esprima_cpp/esprima.cpp:5026
#78 0x0000555555679c30 in Escargot::esprima::Parser::statementListItem<Escargot::esprima::Parser::PassNode<Escargot::StatementNode>, true> (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:3690
#79 0x0000555555658928 in Escargot::esprima::Parser::parseFunctionSourceElements (this=0x7fffffff8ee0) at ../src/parser/esprima_cpp/esprima.cpp:5286
#80 0x000055555565bfcd in Escargot::esprima::parseSingleFunction (ctx=0x7ffff7e5bed0, codeBlock=0x7ffff45bdcb0, stackRemain=3141996) at ../src/parser/esprima_cpp/esprima.cpp:6060
#81 0x0000555555628a6b in Escargot::ScriptParser::parseFunction (this=0x7ffff7e52f70, codeBlock=0x7ffff45bdcb0, stackSizeRemain=3141996, state=0x7fffffffd710) at ../src/parser/ScriptParser.cpp:257
#82 0x00005555556ccc03 in Escargot::FunctionObject::generateBytecodeBlock (this=0x7ffff46311d0, state=...) at ../src/runtime/FunctionObject.cpp:246
#83 0x00005555556cd75c in Escargot::FunctionObject::processCall (this=0x7ffff46311d0, state=..., receiverSrc=..., argc=0, argv=0x7fffffffd610, isNewExpression=false) at ../src/runtime/FunctionObject.cpp:365
#84 0x00005555555f50dc in Escargot::FunctionObject::call (state=..., callee=..., receiver=..., argc=0, argv=0x7fffffffd610, isNewExpression=false) at ../src/runtime/FunctionObject.h:111
#85 0x00005555555f8209 in Escargot::ByteCodeInterpreter::interpret (state=..., byteCodeBlock=0x7ffff7e6bcd0, programCounter=93824999011584, registerFile=0x7fffffffd600, initAddressFiller=0x0) at ../src/interpreter/ByteCodeInterpreter.cpp:529
#86 0x0000555555625d97 in Escargot::Script::execute (this=0x7ffff462cb20, state=..., isEvalMode=false, needNewEnv=false, isOnGlobal=true) at ../src/parser/Script.cpp:79
#87 0x0000555555625ee9 in Escargot::Script::<lambda()>::operator()(void) const (__closure=0x7fffffffd990) at ../src/parser/Script.cpp:92
#88 0x0000555555626ef2 in std::_Function_handler<Escargot::Value(), Escargot::Script::sandboxExecute(Escargot::ExecutionState&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/7/bits/std_function.h:302
#89 0x00005555557bf72c in std::function<Escargot::Value ()>::operator()() const (this=0x7fffffffd990) at /usr/include/c++/7/bits/std_function.h:706
#90 0x00005555557be2df in Escargot::SandBox::run(std::function<Escargot::Value ()> const&) (this=0x7fffffffd900, scriptRunner=...) at ../src/runtime/SandBox.cpp:36
#91 0x0000555555625fc6 in Escargot::Script::sandboxExecute (this=0x7ffff462cb20, state=...) at ../src/parser/Script.cpp:93
#92 0x00005555557dbd0c in eval (context=0x7ffff7e5bed0, str=0x7ffff46297f0, fileName=0x7ffff46296b0, shouldPrintScriptResult=false) at ../src/shell/Shell.cpp:47
#93 0x00005555557dc631 in main (argc=2, argv=0x7fffffffdcb8) at ../src/shell/Shell.cpp:128
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/). </sup>

**Comment by zherczeg** [comment]
```
function test0() {
  (function ($ = function () { }) { });
}
test0();
```
Somewhat simplified test case.

**Comment by zherczeg** [comment]
It looks like this is a scope context problem. The default parameter is instantiated in `test0`, and `this->config.parseSingleFunctionChildIndex` grows by 1. So when the actual body is parsed, we reached the end of child functions.

**Comment by clover2123** [comment]
@zherczeg @rerobika 
Are you working on this issue? I'm going to take this issue if you've not started yet

**Comment by rerobika** [comment]
@clover2123 I've investigated the problem but I don't have proper solution for it, so please feel free to do it.

**Comment by clover2123** [comment]
@rerobika Thanks. I'll take a look at this issue.
